
# .circleci/config.yml
version: 2
jobs:
  build:
    docker:
      - image: circleci/node:6-browsers
        environment:
          JOBS: 2
    working_directory: ~/gitzoom-web
    steps:
      - checkout
      - run:
          name: npm Install
          command: npm install --non-interactive
      - deploy:
          command: |
            if [ "${CIRCLE_BRANCH}" == "master" ]; then
              ember deploy production
            fi